language: java

install: travis_wait 40 mvn -q clean install -Dgib.enabled=true

jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
  env:
    global:
      JAVA_OPTS=-Xmx2g
      MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
